### ISSUE TITLE
Configure no longer works for platforms with regions

### ISSUE THREAD

**Issue by MikeB2013** [honir/tv_grab_uk_atlas#2]
Version 1.012 --configure fails with error:
Not a HASH reference at ./tv_grab_uk_atlas line 1074.

after selecting platform e.g. Freesat, does not get to the point of offering user region selection

Mike

**Comment by honir** [comment]
Interesting - I don't get that error. Hopefully 1.013 (just uploaded) will fix this.

Thanks for the report.

**Comment by MikeB2013** [comment]
Retested --configure  in version 1.013, now working.

Mike
