### ISSUE TITLE
The default setting "publisher=pressassociation.com" is not enabled in Atlas by default

### ISSUE THREAD

**Issue by dreamcat4** [honir/tv_grab_uk_atlas#5]
Hi there,
I really like this Atlas EPG grabber. Is excellent. And well suited for getting all / many kinds of UK listings data. Much better then the previous radiotimes one.

Unfortunately it's not working for me yet. And encounter some "new user" issue. Please forgive me if I haven't understood properly what to do yet.

My problem is this:
When I create a new Atlas API key, then default content providers that are added to it are "BBC" and "UK Channel Lineups".

The initial `tv_grab_uk_atlas --configure` wizard all seem to work OK. I select "UK Freeview", [all] channels etc. It created the config files. Then I run the command `tv_grab_uk_atlas` to download data. It says a 404 error. Then use `--debug` switch to see the full URL of HTTP get request string.

Feeding same URL sting into `curl` program, it says the response is:

```
{"error":{"message":"You must specify at least one publisher that you have permission to view","error_code":"BAD_QUERY_ATTRIBUTE","error_id":"668b84b6-9cff-4686-8526-491aa839eb89"}}
```

Which means I don't have the Press Association (PA) content provider added for my Atlas account / Atlas app. Which is true.

In my Atlas Web interface the "PA" and many other content providers are listed in the section that says "Unavailable… "Request Access". However when I request "PA", it says "it will be added immediately". Yet Atlas does not add it (PA is still disabled). Which isn't the first such behaviour from this buggy web interface. Anyway.

I also cannot see in the `--configure` menus any option to manually choose the publisher and change it in the config file. So that can be `publisher=something-else`. And no option setting gets written in the config file to know correctly the other possible valid publisher strings to use in this field. (Maybe that info is somewhere else on atlas website, I didn't look yet).

So to sum-up:

New user. Atlas API is registered. But `tv_grab_uk_atlas` is not. Because Atlas won't give me the PA (Press Association) content provider. AND I don't know either the correct url string to put `publisher=` for those Content Provider which I do have been given by default (which is named "BBC" and "UK Channel Lineups" in the Atlas Web GUI).

Any help appreciated to get this working. Many thanks.

**Comment by dreamcat4** [comment]
Well…
They added "PA" source for me now. After I created a new API key and requested it (many times yet again). So it's working for me now.

I don't know if you want to improve this Perl code. But maybe add specific error message and quit when you get that response. The user definitely needs to go in to the Atlas Web interface and request access for "PA" source.

You can also PROBE for PA been added during the `--configure` setup step. And tell them at that point that "PA" source needs to be enabled. Which is pretty likely.

**Comment by honir** [comment]
Hi,
Thanks for the feedback and glad you find the grabber useful.

Although you actually got a "Status: 400 Bad Request" (not a 404 as you say in your message) and this is mentioned in the --info page, I appreciate this could be trapped better.  When I wrote this grabber they didn't have the web form process and so all API key requests included Press Association by default, whereas now it is possible to have a key _without_ PA access.

There is no option to manually choose a publisher since the grabber is only designed to work with TV listings from Press Association.

Thanks.

(code revision v1.25)
