### ISSUE TITLE
tv_grab_uk_atlas fails to download listings

### ISSUE THREAD

**Issue by draconis244** [honir/tv_grab_uk_atlas#7]
Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Thu May 19 20:50:46 2016 from 37.152.230.35
root@qehs-tv:~# tv_grab_uk_atlas
Fetching listings:  22% [============                                          ]malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "<!DOCTYPE HTML PUBLI...") at /usr/bin/tv_grab_uk_atlas line 375.
root@qehs-tv:~#

**Comment by draconis244** [comment]
Correctly registered api and asked for PA and UK listings

not sure if its your code or atlas itself sending a malformed bit of data

**Comment by honir** [comment]
Is it repeatable?
Did you ask for more than 24 hours worth of data? (New rules by Metabroadcast limit downloads to 24 hours)
Note the latest version of the grabber is 1.30 and is available from xmltv.org  (this github repository is no longer maintained)
